id: Violation Incident Postprocessing - Group-IB Digital Risk Protection
version: -1
name: Violation Incident Postprocessing - Group-IB Digital Risk Protection
description: Handles postprocessing of violation incidents detected by Group-IB Digital Risk Protection.
fromversion: "6.10.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dd2a29df-d880-4607-86a0-343151471f19
    type: start
    task:
      id: dd2a29df-d880-4607-86a0-343151471f19
      version: -1
      name: Start
      iscommand: false
      brand: ""
      description: Start of the playbook.
    nexttasks:
      '#none#':
      - "1"
    view: "{\"position\": {\"x\": 50, \"y\": 50}}"
  "1":
    id: "1"
    taskid: 547b290a-cd52-43c6-81ee-708c0b3833c9
    type: condition
    task:
      id: 547b290a-cd52-43c6-81ee-708c0b3833c9
      version: -1
      name: Is an action in violation required?
      type: condition
      iscommand: false
      brand: ""
      description: Determines if the incident requires further action.
    nexttasks:
      '#none#':
      - "2"
      "yes":
      - "3"
    view: "{\"position\": {\"x\": 50, \"y\": 220}}"
  "2":
    id: "2"
    taskid: 10df369a-8b31-4bf2-8e2e-123e0dc9c5d7
    type: regular
    task:
      id: 10df369a-8b31-4bf2-8e2e-123e0dc9c5d7
      version: -1
      name: Close Investigation
      description: Close the current incident.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    view: "{\"position\": {\"x\": 50, \"y\": 480}}"
  "3":
    id: "3"
    taskid: 115174e9-015b-4d4a-8f64-d66eee88a54c
    type: regular
    task:
      id: 115174e9-015b-4d4a-8f64-d66eee88a54c
      version: -1
      name: Assign Analyst to Incident
      description: Assign an analyst to investigate the incident.
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      assignBy:
        simple: random
    view: "{\"position\": {\"x\": 470, \"y\": 480}}"
  "4":
    id: "4"
    taskid: 28170cd5-5006-49fc-8558-1f054d607acf
    type: condition
    task:
      id: 28170cd5-5006-49fc-8558-1f054d607acf
      version: -1
      name: Selecting an action with a violation
      type: condition
      iscommand: false
      brand: ""
      description: Determines if the incident should be approved or rejected.
    nexttasks:
      "No":
      - "6"
      Yes, i want:
      - "5"
    view: "{\"position\": {\"x\": 470, \"y\": 660}}"
  "5":
    id: "5"
    taskid: 31ee2b04-5c14-4f26-83db-4c589d9db86f
    type: regular
    task:
      id: 31ee2b04-5c14-4f26-83db-4c589d9db86f
      version: -1
      name: Launching a violation approval
      description: Change the status of the violation to approved.
      script: '|||gibdrp-change-violation-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      id:
        simple: ${incident.gibdrpid}
      status:
        simple: approve
    view: "{\"position\": {\"x\": 470, \"y\": 945}}"
  "6":
    id: "6"
    taskid: 2f0a4e3d-0078-4213-8eb8-ee093fb0fc62
    type: regular
    task:
      id: 2f0a4e3d-0078-4213-8eb8-ee093fb0fc62
      version: -1
      name: Reject Violation
      description: Change the status of the violation to rejected.
      script: '|||gibdrp-change-violation-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      id:
        simple: ${incident.gibdrpid}
      status:
        simple: reject
    view: "{\"position\": {\"x\": 890, \"y\": 945}}"
  "7":
    id: "7"
    taskid: dbb43028-c9d7-4609-89e0-908e87190560
    type: regular
    task:
      id: dbb43028-c9d7-4609-89e0-908e87190560
      version: -1
      name: Done
      description: Close the investigation after processing the violation.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    view: "{\"position\": {\"x\": 680, \"y\": 1170}}"
view: "{\"paper\": {\"dimensions\": {\"height\": 1215, \"width\": 1220, \"x\": 50, \"y\": 50}}}"
tests:
- No tests (auto formatted)
